# 모듈 호출

In [1]:
import tensorflow as tf
import math
import numpy as np

# 데이터 지정

In [2]:
x_data = tf.constant([[0.2,0.6,0.4],[0.1,0.4,0.2],[0.9,0.4,0.2],[0.4,0.1,0.1],[0.5,0.1,0.4]])
output = tf.constant([[0.3,0.2,0.1,0.9],[0.4,0.2,0.2,0.1],[0.9,0.4,0.2,0.1],[0.4,0.1,0.1,0.2],[0.5,0.1,0.4,0.9]])
y_data = tf.constant([[1.0,1.0,0.0,0.0],[1.0,0.0,1.0,0.0],[0.0,0.0,0.0,1.0],[1.0,0.0,0.0,1.0],[1.0,0.0,1.0,0.0]])

In [173]:
np_y_data = np.array([[1.0,1.0,0.0,0.0],[1.0,0.0,1.0,0.0],[0.0,0.0,0.0,1.0],[1.0,0.0,0.0,1.0],[1.0,0.0,1.0,0.0]])

In [174]:
np_y_data

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  1.,  0.]])

In [187]:
c ,d= np.where(np_y_data==1.0)

ValueError: either both or neither of x and y should be given

In [188]:
e,f= np.where(np_y_data==0.0)

In [190]:
c

array([0, 0, 1, 1, 2, 3, 3, 4, 4])

In [191]:
d

array([0, 1, 0, 2, 3, 0, 3, 0, 2])

In [193]:
e

array([0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4])

In [192]:
f

array([2, 3, 1, 3, 0, 1, 2, 1, 2, 1, 3])

In [183]:
a = np.vstack([c,d]).transpose()

In [184]:
a

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 2],
       [2, 3],
       [3, 0],
       [3, 3],
       [4, 0],
       [4, 2]])

In [179]:
a.reshape()

array([0, 1, 0, 2, 3, 0, 3, 0, 2])

In [155]:
C[0]

array([0, 0, 1, 1, 2, 3, 3, 4, 4])

In [122]:
np_y_data.reshape

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  1.,  0.]])

In [164]:
np.vstack([x,y])

array([[0, 0, 1, 1, 2, 3, 3, 4, 4],
       [0, 1, 0, 2, 3, 0, 3, 0, 2]])

In [165]:
x

array([0, 0, 1, 1, 2, 3, 3, 4, 4])

In [112]:
c.reshape(4,4,2)

ValueError: total size of new array must be unchanged

In [89]:
def make_index(y_data):
    one_result = np.array([])
    zero_result = np.array([])
    with tf.Session() as sess:
        tensor_run_y_data = sess.run(y_data)
        for i in tensor_run_y_data:
            print(np.where(i==1.0)[0])
            print(one_result)
            one_result = np.stack([one_result,np.where(i ==1.0)[0]])
        print(one_result)
            #zero_result.append(np.where(i==0.0)[0])
        #return [one_result,zero_result]

In [90]:
make_index_value_list_0_and_1 = make_index(y_data)

[0 1]
[]


ValueError: all input arrays must have the same shape

In [71]:
x = np.arange(0,10,2)                     # x=([0,2,4,6,8])
y = np.arange(5)   

In [72]:
x

array([0, 2, 4, 6, 8])

In [ ]:
np.