In [21]:
import numpy as np
import tensorflow as tf
import math

In [53]:
def make_index(y):
    one_result = []
    zero_result = []
    len_of_x_data = len(y)
    for i in y:
        one_result.append(np.where(i ==1.0)[0])
        zero_result.append(np.where(i==0.0)[0])
    return one_result,zero_result

def select_index_data_of_output(output,index_list):
    data_value_list = []
    for i in range(len(index_list)):
        data_value_list.append([])
        cnt = 0
        data_value_list[i].append([])
        for k in range(len(index_list[i][0])):
            
            data_value_list[i][cnt].append(output[:,k])
        cnt +=1
        data_value_list[i].append([])
        for j in range(len(index_list[i][1])):
            data_value_list[i][cnt].append(output[:,j])
    return data_value_list

def make_cartesian_list(x):
    cartesian_list = []
    yi_length = []
    nyi_length = []
    for i in range(len(x)):
        yi_length.append(len(x[i][0]))
        nyi_length.append(len(x[i][1]))
        cartesian_list.append([])
        for j in x[i][0]:
            for k in x[i][1]:
                cartesian_list[i].append([j,k])
    return cartesian_list,yi_length,nyi_length

def bp_mll_exp_function(cartesian_list_instance):
    return tf.exp(cartesian_list_instance[1]-cartesian_list_instance[0])

def get_error(cartesian_list):
    global_error = 0
    cnt = 0
    for docu in cartesian_list[0]:
        for instance in docu:
            global_error += 1/cartesian_list[1][cnt]*cartesian_list[2][cnt]* bp_mll_exp_function(instance)
    return global_error

In [54]:
x_data = np.array([[0.1,0.9,0.1],[0.9,0.1,0.1]],dtype='float32')
y_data = np.array([[0.0,1.0,0.0],[1.0,0.0,0.0]],dtype='float32')

In [94]:
# Load data

# Graph input
X = tf.placeholder("float", [2,3] )
# Model weight
W = tf.Variable(tf.random_uniform([3,3],-1.0,1.0))

# Construct model

hypothesis = tf.nn.softmax(tf.nn.relu(tf.matmul(X,W)))
y_data_index = make_index(y_data)
x_data_index_value = select_index_data_of_output(hypothesis,y_data_index)
cartesian_list= make_cartesian_list(x_data_index_value)
cost=get_error(cartesian_list)

a = tf.Variable(0.01)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)
    for step in range(100000):
        sess.run(train,feed_dict={X:x_data})
        if step %10000 == 0:
        
            print(sess.run(hypothesis,feed_dict={X:x_data}))
        
        
        

[[ 0.3484309   0.36040413  0.29116502]
 [ 0.39279279  0.39225549  0.21495169]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]
[[ 0.35438699  0.35439232  0.29122072]
 [ 0.39252558  0.3925209   0.21495353]]


In [83]:
print(hypothesis.eval)

<bound method Tensor.eval of <tf.Tensor 'Softmax_39:0' shape=(2, 3) dtype=float32>>
